config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'chatroom#index'

  #post/get/delete are the functions of routes. One sends info, one gets and one destroys.
  #the to: function directs it to a controller method. In this case, messages controller
  #and the create method --> def create section.
  post 'message', to: 'messages#create'
  mount ActionCable.server, at: '/cable'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true, length: { minimum: 1, maximum: 250 }
  scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


         private 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!


end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @message = Message.new
    @messages = Message.custom_display
  end

end

app/controllers/concerns/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel",
                                    mod_message: message_render(message)
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: {message: message})
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :last_name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :last_name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <h2 class="ui center aligned icon header">
  <i class="comments outline icon"></i>
  Chatroom
</h2>
  </head>
  <body>
    <div class="ui two column grid">
      <div class="twelve wide column">
        <div class="ui fluid raised card chatbox">
          <div class="content" id="messages">
            <div class="ui feed" id="message-container">
    <%= render @messages %>
  </div>
</div>
  <div class="extra content">
    <%= form_for(@message, html: {class: "ui reply form"}, url: message_path,remote: true) do |f|%>
    <form class="ui reply form">
      <div class="field">
        <div class="ui fluid icon input">
          <%= f.text_field :body %>
          <%= f.button '<i class="bordered inverted blue icon edit"></i>'.html_safe %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

<div class="four wide column">
  <div class="ui fluid raised card chatbox">
    <div class="content">
    <div class="ui secondary vertical menu">
      <a class="active item">
        Account
      </a>
      <a class="item">
        Settings
      </a>
      <div class="ui dropdown item">
        <i class="dropdown icon"></i>
        Display Options
        <div class="menu">
          <div class="header">Text Size</div>
          <a class="item">Small</a>
          <a class="item">Medium</a>
          <a class="item">Large</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


  </body>
</html>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui small menu">
  <div class="ui container">
    <%= link_to "Chatroom", root_path, class:"item"%>
    <a class="item">
    Messages
    </a>
    <div class="right menu">
      <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
          <div class="menu">
            <% if user_signed_in? %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "item" %>
            <%= link_to "Settings", edit_user_registration_path, class: "item" %>
            <% else %>
            <%= link_to "Log in", new_user_session_path, method: :post, class: "item" %>
            <%= link_to "Sign up", new_user_registration_path, class: "item" %>
            <% end %>
              </div>
            </div>
            <% if user_signed_in? %>
          <div class="item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "ui red button" %>
          </div>
            <% else %>
            <div class="item">
            <%= link_to "Log in", new_user_session_path, class: "ui primary button" %>
            </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<%= render "layouts/navigation"%>
  <body>
    <div class="ui container">
      <%= render 'layouts/messages' %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username %></em>: <%= message.body %>
    </div>
  </div>
</div>